---


# Parameters for pre-processing reads
adapter: "TGGAATTCTCGGGTGCCAAGG"
minlength: "18"
maxlength: "100"
qualcutoff: "20"


# Parameters for mapping
contaminants: "resources/contaminants.combined_human_yeast.fa"
genome: "resources/genome.combined_human_yeast.fa"
gtf: "resources/annotation.combined_human_yeast.gtf"
platform: "Illumina"


# Parameters for spike-in processing
human_chromosomes: "resources/chromosomes.human.bed"
human_contaminants: "resources/contaminants.human.bed"
yeast_chromosomes: "resources/chromosomes.yeast.bed"
yeast_contaminants: "resources/contaminants.yeast.bed"


# Parameters for RiboseQC, ORFquant, and RiboStan
# Human
human_genome: "resources/GRCh38.primary_assembly.genome.fa"
human_transcriptome: "resources/HCT116_Txome_WT.v1.0.sort.fa"
human_gtf: "resources/HCT116_Txome_WT.v1.0.sort.gtf"

# Yeast
yeast_genome: "resources/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa"
yeast_transcriptome: "resources/Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa"
yeast_gtf: "resources/Saccharomyces_cerevisiae.R64-1-1.109.gtf"


# Parameters for Salmon (for total RNA quantification)
transcriptome: "resources/transcriptome.combined_human_yeast.fa"