#!/bin/bash


cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4E_minus_rep1_01_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_minus_4hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4E_minus_rep2_02_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_minus_4hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4E_minus_rep3_03_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_minus_4hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4E_plus_rep1_04_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_plus_4hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4E_plus_rep2_05_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_plus_4hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4E_plus_rep3_06_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_plus_4hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_oldmonosome4G1_minus_rep1_07_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_minus_4hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_oldmonosome4G1_minus_rep2_08_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_minus_4hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_oldmonosome4G1_minus_rep3_09_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_minus_4hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_oldmonosome4G1_plus_rep1_10_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_plus_4hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_oldmonosome4G1_plus_rep2_11_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_plus_4hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_oldmonosome4G1_plus_rep3_12_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_plus_4hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G2_minus_rep1_13_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_minus_4hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G2_minus_rep2_14_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_minus_4hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G2_minus_rep3_15_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_minus_4hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G2_plus_rep1_16_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_plus_4hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G2_plus_rep2_17_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_plus_4hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G2_plus_rep3_18_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_plus_4hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G3_minus_rep1_19_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_minus_4hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G3_minus_rep2_20_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_minus_4hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G3_minus_rep3_21_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_minus_4hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G3_plus_rep1_22_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_plus_4hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G3_plus_rep2_23_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_plus_4hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_CCDS/results/post/psitecov_ribo_4G3_plus_rep3_24_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_plus_4hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4E_minus_rep1_01_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_minus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4E_minus_rep2_02_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_minus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4E_minus_rep3_03_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_minus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4E_plus_rep1_04_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_plus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4E_plus_rep2_05_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_plus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4E_plus_rep3_06_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4E_plus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G1_minus_rep1_07_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_minus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G1_minus_rep2_08_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_minus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G1_minus_rep3_09_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_minus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G1_plus_rep1_10_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_plus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G1_plus_rep2_11_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_plus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G1_plus_rep3_12_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G1_plus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G2_minus_rep1_13_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_minus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G2_minus_rep2_14_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_minus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G2_minus_rep3_15_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_minus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G2_plus_rep1_16_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_plus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G2_plus_rep2_17_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_plus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G2_plus_rep3_18_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G2_plus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G3_minus_rep1_19_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_minus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G3_minus_rep2_20_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_minus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G3_minus_rep3_21_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_minus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G3_plus_rep1_22_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_plus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G3_plus_rep2_23_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_plus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4G3_plus_rep3_24_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4G3_plus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4wt_minus_rep1_25_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4wt_minus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4wt_minus_rep2_26_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4wt_minus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4wt_minus_rep3_27_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4wt_minus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4wt_plus_rep1_28_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4wt_plus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4wt_plus_rep2_29_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4wt_plus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif4f_8h/results/post/psitecov_ribo_4wt_plus_rep3_30_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_4wt_plus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_minusAuxin_minusHarr_4h_rep1_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_minus_4hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_minusAuxin_minusHarr_4h_rep2_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_minus_4hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_minusAuxin_minusHarr_4h_rep3_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_minus_4hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_minusAuxin_minusHarr_8h_rep1_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_minus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_minusAuxin_minusHarr_8h_rep2_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_minus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_minusAuxin_minusHarr_8h_rep3_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_minus_8hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_plusAuxin_minusHarr_4h_rep1_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_plus_4hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_plusAuxin_minusHarr_4h_rep2_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_plus_4hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_plusAuxin_minusHarr_4h_rep3_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_plus_4hours_rep3.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_plusAuxin_minusHarr_8h_rep1_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_plus_8hours_rep1.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_plusAuxin_minusHarr_8h_rep2_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_plus_8hours_rep2.bedgraph
cp /fast/AG_Ohler/gabriel/eif3d/results/post/psitecov_ribo_eIF3D_plusAuxin_minusHarr_8h_rep3_R1.bedgraph /data/bimsbstatic/public/ohler/gabriel/psite_profiles/psitecov_ribo_eIF3D_plus_8hours_rep3.bedgraph




